services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    image: fastapi_app
    environment:
      # TODO: Move env variables to the .env file
      - DATABASE_URL=postgres://postgres:test123@:5432/mydatabase
    volumes:
      # INFO: this is a bind
      - ./:app
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      # TODO: Move env variables to the .env file
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres`
      - POSTGRES_PASSWORD=test123
    volumes:
      - postgres_data/var/lib/postgresql/data

volumes:
  postgres_data:
